# Generated by Django 3.1.4 on 2021-01-07 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название пути')),
            ],
            options={
                'verbose_name': 'Путь',
                'verbose_name_plural': 'Пути',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание тура')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stars', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Кол-во звёзд')),
                ('contry', models.CharField(blank=True, max_length=30, null=True, verbose_name='Страна тура')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата начла тура')),
                ('duration', models.PositiveSmallIntegerField(default=0, verbose_name='Продолжительность тура')),
                ('depature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               to='tours.depature', verbose_name='Название пути')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
    ]
