# Generated by Django 3.1.4 on 2021-01-07 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tours', '0002_mainpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainPage',
        ),
    ]
