# Generated by Django 3.1.4 on 2021-01-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tours', '0003_delete_mainpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='depature',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, null=True, verbose_name='Слаг'),
        ),
    ]
