# Generated by Django 3.1.4 on 2021-01-07 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tours', '0004_depature_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='contry',
            new_name='country',
        ),
    ]
